version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: navuchai_app
    restart: always
    env_file:
      - .env
    ports:
      - "8012:8012"
    volumes:
      - .:/app        # для автообновления кода
    command: uvicorn app.main:app --host 0.0.0.0 --port 8012 --reload
